# -*- coding: utf-8 -*-
"""Untitled48.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13_tXcSuJEDpDjfNcK4dWJx5pFaXlIxc-
"""

import googletrans
import translate
import streamlit as st

st.title("Translator")

translator = googletrans.Translator()
List_LANGUAGES = googletrans.LANGUAGES

user_input = st.text_input("Enter Text:")


languages = []

for code, name in List_LANGUAGES.items():
    languages.append({name: code})

# SEPARATING NAME & CODE
languages_name = [list(i.keys())[0] for i in languages]
lan_codes = [list(i.values())[0] for i in languages]

selected_languages = st.selectbox('', languages_name)

code = lan_codes[languages_name.index(selected_languages)]

# TRANSLATING
def translate_lan(text):
    try:
        translated = translator.translate(text, dest=code)
        translated_text = translated.text
        return translated_text
    except Exception as e:
        pass

tran = translate_lan(user_input)
if tran ==None:
    pass
else:
    st.header(tran)